### ISSUE TITLE
Thanks for sharing this project.

### ISSUE THREAD

**Issue by azhizhinov** [semickolon/fak#1]
Hello.
Is there some example for 60% keyboard with CH552, I'm not so experienced in this?
All I've found it's macropads with 4-8 keys and an encoder.
Is there any possibility to make split keyboards with CH552?
Thanks in advance.

**Comment by semickolon** [comment]
Official reference keyboards will be out soon so the community can easily try FAK out and make designs off of.

CH552 doesn't have enough pins for a 60% keyboard in regular matrix scanning. CH558/9L does have enough pins but I haven't tested it on those chips yet. I'm experimenting with [round-robin scanning](https://kbd.news/Improved-square-matrix-1415.html) to make a 60%+ possible even with a CH552.

Until split KB support is out, it's not possible at the moment.
