### ISSUE TITLE
ERROR: Tried to access unknown option 'split'.

### ISSUE THREAD

**Issue by sebastian-stumpf** [semickolon/fak#5]
I'm trying to get FAK running on Ubuntu 22.04.3 LTS. So far I've just checked out the repository and executed executed `python fak compile` to check if everything is working, but I'm running into an error: `Tried to access unknown option 'split'.` I've tried it with the system Python version 3.10 and also with 3.11.7 installed via pyenv. The result is always the same.

Full output:

```
{teadrunk:~/workspace/fak} {0} % python fak.py compile
The Meson build system
Version: 0.61.2
Source dir: /home/teadrunk/workspace/fak
Build dir: /home/teadrunk/workspace/fak/build
Build type: native build
Project name: fak
Project version: undefined
C compiler for the host machine: ccache cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program sdcc found: YES (/usr/bin/sdcc)
Program nickel found: YES (/home/teadrunk/.cargo/bin/nickel)
Program python found: YES (/home/teadrunk/.pyenv/versions/3.11.7/bin/python)
Program wchisp found: YES (/home/teadrunk/.cargo/bin/wchisp)

meson.build:31:3: ERROR: Tried to access unknown option 'split'.

A full log can be found at /home/teadrunk/workspace/fak/build/meson-logs/meson-log.txt
Traceback (most recent call last):
  File "/home/teadrunk/workspace/fak/fak.py", line 140, in <module>
    subcmd_compile()
  File "/home/teadrunk/workspace/fak/fak.py", line 95, in subcmd_compile
    meson_configure()
  File "/home/teadrunk/workspace/fak/fak.py", line 83, in meson_configure
    subprocess.run(['meson', 'setup', BUILD_DIR], check=True)
  File "/home/teadrunk/.pyenv/versions/3.11.7/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['meson', 'setup', 'build']' returned non-zero exit status 1.
```

I'm not sure if this is a bug or if I did something wrong. Is there anything I can try to hunt down the root of this issue?

**Comment by sebastian-stumpf** [comment]
sdcc: SDCC : mcs51/z80/z180/r2k/r3ka/gbz80/tlcs90/ez80_z80/ds390/TININative/ds400/hc08/s08/stm8/pdk13/pdk14/pdk15 4.0.0 #11528 (Linux)
nickel: nickel-lang-cli nickel 1.3.0 (rev cargore)
meson: 0.61.2
ninja: 1.10.1
wchisp: wchisp 0.2.2

**Comment by semickolon** [comment]
Looks like it's not picking up `meson.options`. I checked and you need at least meson 1.1.0 for it to read the .options file:
https://mesonbuild.com/Release-notes-for-1-1-0.html#support-for-reading-options-from-mesonoptions

If that still doesn't work, try the meson version used in the Nix flake, which is 1.2.3

**Comment by sebastian-stumpf** [comment]
That's it! I've just installed meson via pip and now everything works. Thank you very much for your help!
